### ISSUE TITLE
Logo source file?

### ISSUE THREAD

**Issue by sindresorhus** [RaptureCore/Rapture#7]
Where can I find the source file or SVG (not PNG) of the project logo?

I would like to submit it to https://github.com/hyperdexapp/cryptocurrency-icons

**Comment by Robitussin-DM** [comment]
@RaptureCore This can be closed.

**Comment by sindresorhus** [comment]
Sure. For anyone working on Rapture, I have vectorized the logo for you here if you want it: https://github.com/atomiclabs/cryptocurrency-icons/issues/192
